### PR TITLE
adds homebrew method for OS X

### PR DESCRIPTION
**Pull request by pyed**

### CODE REVIEW

**Comment by mcrapet** [comment]
Hi,

The [plowshare homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/plowshare.rb) appears quite old. tesseract has been dropped since july, 2012!

I think we should first improve the recipe rather than plowshare INSTALL file.
I'll add the simple: `$ homebrew plowshare` line when recipe will be fixed.

Could you test this: http://sprunge.us/cXhU
What is the bottle bloc ?

**Comment by pyed** [comment]
your formula works just switch `GNU_SED=/opt/bin/gnu-sed` for `GNU_SED=/usr/local/bin/gsed`

the bottle block contains info for the "bottled" version of the formula, which is just a pre-compiled binary for the last 3 OS X versions, and what you see here is the checksums, it should be left for the home-brew guys.

**Comment by mcrapet** [comment]
Thanks for testing :)

Is there a special variable for `/usr/local/bin` like `#{bindir}` ?

**Comment by mcrapet** [comment]
According to other recipes, it appears to be `#{bin}`

**Comment by mcrapet** [comment]
@pyed Is this okay for you ?
http://sprunge.us/VVEF

If so, I'll send them a PR.

**Comment by pyed** [comment]
this `#{bin}/gsed` expands to `/usr/local/Cellar/plowshare/2.1.4/bin/gsed` which is wrong 

I couldn't find a resource for all the variables, I'll keep looking

**Comment by pyed** [comment]
`"GNU_SED=#{HOMEBREW_PREFIX}/bin/gsed"` works

I've seen some formulas use it

**Comment by mcrapet** [comment]
https://github.com/Homebrew/homebrew-core/pull/1196

I bypassed this:
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

**Comment by pyed** [comment]
`brew audit --strict --online plowshare` complains about not having a test block.

here's a test block from `wget`'s formula 

``` ruby
test do
    system bin/"wget", "-O", "-", "https://google.com"
end
```

what kind of test is suitable for plowshare ?

**Comment by pyed** [comment]
after looking at `wget`'s formula test block, looks like we just needed `GNU_SED=bin/gsed`

**Comment by mcrapet** [comment]
A guy commented PR.

Could you test (for the last time I hope):
https://raw.githubusercontent.com/mcrapet/homebrew-core/64a04bb78b359c34638087e5c4cd74a59517f050/Formula/plowshare.rb

**Comment by pyed** [comment]
yes, that works, it should be the right way to do it.

**Comment by mcrapet** [comment]
PR has been accepted. I'll update INSTALL.
Thanks for your help.

**Pull request closed without merging**
